theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = true

#[editor.cursor-shape]
#insert = "block"
#normal = "block"
#select = "block"

[editor.file-picker]
hidden = false

#[editor.soft-wrap]
#enable = true
