###############################################################
#
# Configuration documentation is available at
#     https://dystroy.org/broot
#
###############################################################

# Show hidden and gitignored files in search
default_flags = "hg"

# date_time_format: %Y/%m/%d %R

# Mark the selected line with a triangle
show_selection_mark = true

# Allows more than 2 splits at once
max_panels_count = 2

# See https://dystroy.org/broot/icons for more info
# Comment out for no icons
# icon_theme = "vscode"

# Bigger files are ignored when searching their content. 
content_search_max_file_size = "5MB"

###############################################################
# uncomment to activate modal mode
#
# (you really should read https://dystroy.org/broot/modal/
# before as it may not suit everybody even among vim users)
#
# modal: true
#
###############################################################


###############################################################
# Column order
# cols_order, if specified, must be a permutation of the following
# array. You should keep the name column at the end as it has a
# variable length.
#
# cols_order: [
#     mark
#     git
#     size
#     permission
#     date
#     count
#     branch
#     name
# ]

###############################################################
# True Colors
# If this parameter isn't set, broot tries to automatically
# determine whether true colors (24 bits) are available.
# As this process is unreliable, you may uncomment this setting
# and set it to false or true if you notice the colors in
# previewed images are too off.
#
# true_colors: false


# Special paths
# If some paths must be handled specially, uncomment (and change
# this section as per the examples)
# [special_paths]
# "/media" = "no-enter" 
# "/media/slow-backup-disk"    : no-enter
# "/home/dys/useless"    : hide
# "/home/dys/my-link-I-want-to-explore"    : enter

###############################################################
# Quit on last cancel
# You can usually cancel the last state change on escape.
# If you want the escape key to quit broot when there's nothing
# to cancel (for example when you just opened broot), uncomment
# this parameter
# 
# quit_on_last_cancel: true

###############################################################
# Search modes
#
# broot allows many search modes.
# A search mode is defined by
# - the way to search: 'fuzzy', 'exact', 'regex', or 'tokens'.
# - where to search: file 'name', 'path', or file 'content'
# A search pattern may for example be "fuzzy path" (default),
# "regex content" or "exact path".
#
# The search mode is selected from its prefix. For example, if
# you type "abc", the default mode is "fuzzy path". If you type
# "/abc", the mode is "regex path". If you type "rn/abc", the mode
# is "regex name".
#
# This mapping may be modified. You may want to dedicate the
# empty prefix (the one which doesn't need a '/') to the
# search mode you use most often. The example below makes it
# easy to search on name rather than on the subpath.
#
# More information on
#  https://dystroy.org/broot/input/#the-filtering-pattern
#
# search_modes: {
#     <empty>: fuzzy name
#     /: regex name
# }


###############################################################
# File Extension Colors
[ext_colors]
png = "rgb(255, 128, 75)"
rs = "yellow"
toml = "ansi(105)"
###############################################################



