#!/bin/sh

image() {
	geometry="$(($2-2))x$3"
	echo "$1" "$geometry" >> /tmp/lf.log
	chafa "$1" -f img2sixel -s "$geometry" --animate false | fold -w 65535
}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

# for some reason .m4a are read as videos
case "$(file --dereference --brief --mime-type -- "$1")" in
	*.tgz |*.tar.gz) tar tzf "$1" ;;
	# *.tar.bz2|*.tbz2) tar tjf "$1" ;;
	# *.tar.txz|*.txz) xz --list "$1" ;;
	# *.tar) tar tf "$1" ;;
	# *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1" ;;
	# *.rar) unrar l "$1" ;;
	# *.7z) 7z l "$1" ;;
	# *.[1-8]) man "$1" | col -b ;;
	*.o) nm "$1";;
	# *.torrent) transmission-show "$1" ;;
	# *.odt|*.ods|*.odp|*.sxw) odt2txt "$1" ;;
	# *.doc) catdoc "$1" ;;
	# *.docx) docx2txt "$1" ;;
        # *.xml|*.html) w3m -dump "$1";;
 	audio/*) mediainfo "$1" ;;
	text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
	# *.pdf)
		# [ ! -f "${CACHE}.jpg" ] && \
		# 	pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		# image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
		# ;;
	# *.epub)
	# 	[ ! -f "$CACHE" ] && \
	# 		epub-thumbnailer "$1" "$CACHE" 1024
	# 	image "$CACHE" "$2" "$3" "$4" "$5"
	# 	;;
	# *.cbz|*.cbr|*.cbt)
	# 	[ ! -f "$CACHE" ] && \
	# 		comicthumb "$1" "$CACHE" 1024
	# 	image "$CACHE" "$2" "$3" "$4" "$5"
	# 	;;
	# video/* )
	# 	[ ! -f "${CACHE}.jpg" ] && \
	# 		ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
	# 	image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
	# 	;;
	image/*) image "$1" "$2" "$3" "$4" "$5" "$1" ;;
 #  *.svg)
 #    [ ! -f "${CACHE}.jpg" ] && \
 #      convert "$1" "${CACHE}.jpg"
 #    image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
 #    ;;
 #
	text/troff) man ./ "$1" | col -b ;;
	text/* | application/json) bat --plain --color always "$1" ;;
esac
# 	*/pdf)
# 		CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
# 		[ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
# 		image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
# 		;;
# 	application/pgp-encrypted) gpg -d -- "$1" ;;
# esac

exit 0
