#!/bin/bash

## Open Applications
cmd="handlr open"

if [[ "$1" == "--firefox" ]]; then
	eww close-all && brave &

elif [[ "$1" == "--telegram" ]]; then
	eww close-all && telegram-desktop &

elif [[ "$1" == "--github" ]]; then
	eww close-all && $cmd "https://github.com" &

elif [[ "$1" == "--reddit" ]]; then
	eww close-all &&  $cmd "https://reddit.com" &

elif [[ "$1" == "--code" ]]; then
	eww close-all && emacsclient &

elif [[ "$1" == "--discord" ]]; then
	notify-send "Discord not installed"
    # eww close-all && discord &

elif [[ "$1" == "--spotify" ]]; then
	eww close-all && foot -e ncmpcpp &
fi
