add_newline = false
scan_timeout = 10

format = """(fg:#fff1cf)$username$directory$battery$git_branch$git_status$character""" 

[line_break]
disabled = false

[fill]
symbol = " "
style = "fg:#252525 bg:#6f6565"

[character]
success_symbol = "[](bold cyan)"
error_symbol = "[](bold red)"

[git_branch]
format = "$symbol$branch [](fg:#6f6565 bold)[](bg:#6f6565 fg:#fff1cf)[](fg:#6f6565) "
symbol = " "

[directory]
format = "[$path]($style)[$read_only]($style)[ ](fg:#6f6565 bold)"
style = "fg:#fff1cf bg:#6f6565"
truncation_symbol = "…/"
truncate_to_repo = false 
truncation_length = 100
home_symbol = "  "

[username]
format = "[](fg:#fff1cf bold)[ ](fg:#252525 bg:#fff1cf bold)[](fg:#fff1cf bg:#6f6565 bold)"
show_always = true
disabled = false
