#!/bin/sh

code=""
cmd=""
cmd_file=$(mktemp)
if broot --outcmd "$cmd_file" "$@"; then
  cmd=$(<"$cmd_file")
  command rm -f "$cmd_file"
  # if "$cmd": 
  # eval "alacritty -e $cmd"
  eval "$cmd"
else
  code=$?
  command rm -f "$cmd_file"
  return "$code"
fi
