#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/ewwdashboard.xyz"
DASHBOARD="$HOME/.config/eww/dashboard"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 2
fi

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	sh ${DASHBOARD}/../scripts/quotes update
	${DASHBOARD}/../scripts/getweather --getdata
	eww -c ${DASHBOARD} open dashboard
else
	eww -c ${DASHBOARD} close-all 
	rm "$FILE"
fi
