#!/bin/sh

# . $HOME/.local/bin/env-wayland.sh # this just sources a few extra env variables

# Default things
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_CURRENT_DESKTOP=Hyprland

# Bug fixing
export WLR_RENDERER_ALLOW_SOFTWARE=1
export LIBSEAT_BACKEND=logind

exec dbus-run-session Hyprland $@
