#!/bin/sh

# err() { echo "Usage:
#     tag [OPTIONS] file
# Options:
#     -a: artist/author
#     -t: song/chapter title
#     -A: album/book title
#     -n: track/chapter number
#     -N: total number of tracks/chapters
#     -d: year of publication
#     -g: genre
#     -c: comment
# You will be prompted for title, artist, album and track if not given." && exit 1 ;
# }

# while getopts "a:t:A:n:N:d:g:c:" o; do case "${o}" in
#     a) artist="${OPTARG}" ;;
#     t) title="${OPTARG}" ;;
#     A) album="${OPTARG}" ;;
#     n) track="${OPTARG}" ;;
#     N) total="${OPTARG}" ;;
#     d) date="${OPTARG}" ;;
#     g) genre="${OPTARG}" ;;
#     c) comment="${OPTARG}" ;;
#     *) printf "Invalid option: -%s\\n" "$OPTARG" && err ;;
# esac done

file="$1"

temp="$(mktemp)"
trap 'rm -f $temp' HUP INT QUIT TERM EXIT

[ ! -f "$file" ] && echo 'Provide file to tag.' && exit 1

vorbiscomment -l "$file" -c "$temp"
grep "language=" $temp || echo "language=" >> $temp
grep "artist=" $temp || echo "artist=" >> $temp
grep "title=" $temp || echo "title=" >> $temp
grep "album=" $temp || echo "album=" >> $temp
grep "track=" $temp || echo "track=" >> $temp
grep "total=" $temp || echo "total=" >> $temp
grep "tags=" $temp || echo "tags=" >> $temp
grep "genre=" $temp || echo "genre=" >> $temp
grep "comment=" $temp || echo "comment=" >> $temp

$EDITOR $temp
vorbiscomment -w "$file" -c "$temp"

# [ -z "$title" ] && echo 'Enter a title.' && read -r title
# [ -z "$artist" ] && echo 'Enter an artist.' && read -r artist
# [ -z "$album" ] && echo 'Enter an album.' && read -r album
# [ -z "$track" ] && echo 'Enter a track number.' && read -r track
#
# cp -f "$file" "$temp" && ffmpeg -i "$temp" -map 0 -y -codec copy \
#     -metadata title="$title" \
#     -metadata album="$album" \
#     -metadata artist="$artist" \
#     -metadata track="${track}${total:+/"$total"}" \
#     ${date:+-metadata date="$date"} \
#     ${genre:+-metadata genre="$genre"} \
#     ${comment:+-metadata comment="$comment"} "$file"
