#!/usr/bin/env bash

## Author  : Aditya Shakya
## Mail    : adi1090x@gmail.com
## Github  : @adi1090x
## Twitter : @adi1090x

rofi_command="rofi -theme $HOME/.config/rofi/style/tray.rasi"
# can also use app.rasi
# this exist somewhere good look finding it


# Links
terminal=""
files=""
editor=""
browser=""
music=""
settings=""



# Variable passed to rofi
options="$terminal\n$files\n$editor\n$browser\n$music\n$settings"

chosen="$(echo -e "$options" | $rofi_command -p "Most Used" -dmenu -selected-row 0)"
case $chosen in
    $terminal)
		foot -d none &
	;;
    $files)
		foot -d none -e lf &
    ;;
    $editor)
		foot -d none -e helix &
    ;;
    $browser)
		brave &
	;;
    $music)
		foot -d none -e ncmpcpp &
    ;;
    $settings)
        # Open in config. stay in fish after exiting
		foot -d none -H -D ~/.config -e fish -C br 
    ;;
esac

