#!/usr/bin/env zsh

source "${HOME}/.local/share/zsh/zgenom/zgenom.zsh"

# if the init script doesn't exist
if ! zgenom saved; then
# specify plugins here
  zgenom ohmyzsh

  # generate the init script from plugins above
  zgenom save
fi

zgenom autoupdate

zgenom load Aloxaf/fzf-tab
# zgenom load jeffreytse/zsh-vi-mode
zgenom load zsh-users/zsh-syntax-highlighting
zgenom load zsh-users/zsh-completions src
# zgenom load zsh-users/zsh-autosuggestions
# zgenom load zsh-users/zsh-history-substring-search
# zgenom load romkatv/powerlevel10k powerlevel10k
while read file
do 
done <<-EOF
theme
EOF


# Alias for commands I use often
# alias chad='startx ~/.config/chadwm/scripts/run.sh'
# alias sudo='doas'
alias ce="chezmoi edit"
alias c="chezmoi"
alias v="nvim"
alias rm="trash-put"
alias ls='exa --color=auto --icons' # my preferred listing
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
alias svim='sudoedit'
alias lg="lazygit"
export TERM='xterm-256color'
export EDITOR='nvim'
export VISUAL='nvim'
# alias lf='lfrun'
alias m='neomutt'
alias r='newsboat' 
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)' # remove orphaned packages
path+=('/home/aspect/.config/emacs/bin')
path+=('/home/daniel/.local/share/cargo/bin')
path+=('/home/aspect/.local/bin')
# ~/.config/tmux/plugins
export PATH=$HOME/.config/tmux/plugins/t-smart-tmux-session-manager/bin:$PATH
export PATH=$HOME/.config/emacs/bin:$PATH
export PATH

alias wgu="sudo wg-quick up nebula"
alias wgd="sudo wg-quick down nebula"



alias gl='git clone'
alias de='doasedit'

eval "$(starship init zsh)"

alias ttc='tty-clock -c -C 7 -r -f "%A, %B %d"'

command_not_found_handler() {
  printf 'Command not found ->\033[32;05;16m %s\033[0m \n' "$0" >&2
  return 127
}

export SUDO_PROMPT=$'Password for ->\033[32;05;16m %u\033[0m  '


chpwd() {
    exa --icons -a
}

dotgit() {
    gitdir="/home/daniel/.local/share/chezmoi"
    git -C $gitdir add .
    git -C $gitdir commit -m "$*"
    git -C $gitdir push
}

# Cheat query
cht() {
    curl -s "cheat.sh/$(echo -n "$*" | jq -sRr @uri)"
}

lf () {
    tmp="$(mktemp)"
    # `command` is needed in case `lfcd` is aliased to `lf`
    command lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}


bindkey '^f' lf

eval "$(zoxide init zsh)"

export FZF_DEFAULT_OPTS='
  --color fg:#b6beca,bg:#13171b
  --color bg+:#ef7d7d,fg+:#2c2f30
  --color hl:#dadada,hl+:#13171b,gutter:#13171b
  --color pointer:#373d49,info:#606672
  --border
  --color border:#13171b
  --height 13'

export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"



[ -f ~/.config/zsh/.fzf.zsh ] && source ~/.config/zsh/.fzf.zsh
